---
title: "Student Hours"
toc: false
--- 

# Student Hours

<br>

## 💬 Instructor Student Hours

**When:** By appointment

**Where:** Carmen's office (Bren Hall 4024) or Zoom

I’m here to help! **Office hours are by appointment—just send me a message via email or Slack**, and we’ll find a time that works for you or your team. Supporting each student and team with their capstone project is a top priority, so don’t hesitate to reach out. Looking forward to working with you!

**Contact:**  e-mail (c_galazgarcia@ucsb.edu) or  Slack

<br>

## 📊 TA Student Hours

**When:** Tuesday and Thursday, 2 pm - 5 pm 

**Where:** Allie's office (Bren Hall 3313) or Zoom

Our class TA, Allie Caughman, is here to help! 

**Use [this calendar](https://tinyurl.com/EDS411A-OH) to schedule a time that works for you.**

- **Before your appointment, please fill out [this form](https://forms.gle/vqDJFWtkpqR31Tf19) to share your question or problem.**
- Each team can book up to 45 minutes per week using the link above.
- Appointments are available in 15-minute slots throughout the quarter.
- Appointments outside of these times may be requested. 
- Drop by for quick questions—just double-check that Sandy isn’t already in a scheduled appointment.

**Contact:**  e-mail (acaughman@bren.ucsb.edu) or Slack
