---
title: "Spring Week 4"
---

## Materials

📕 [Class slides]({{< var spring-week4-class-slides >}})

📗 [Unit Testing for Web Apps Workshop - 
Sam Shanny-Csik]({{< var unit-testing-for-web-apps-slides >}})

💭 [In-class team reflections]({{< var team-reflections-411B >}})

📖 [Capstone guidelines]({{< var capstone-guidelines >}})

## Schedule

12:30 - ~1:45: Unit Testing Web Apps Workshop - Sam Shanny-Csik

~1:45 - 2:00: Break

2:00 - 2:10: Questions, Check-in, & Upcoming assignments

2:10 - 3:20: Independent co-working & meetings with teams

3:20 - 3:30: Team reflections



## Upcoming deadlines

{{< include _spring_deadlines_tables.qmd >}}

<div id="table-week4-7"></div>

## To do by next week

### 1. 🌱 Complete Personal Reflection 1 & Self/Peer evaluation

**Due when?** Submit by next class {{< var spring-week5-class-date >}}.

**How to submit:** Upload the two documents **as PDFs** to [this Box folder]({{< var reflection-1-box-folder-411B >}}). Make sure you use the following file names:

1. `YourGroupAlias_Firstname_Lastname_411B_CapstoneReflection1.pdf`
2. `YourGroupAlias_Firstname_Lastname_411B_SelfPeerEvaluation1.pdf`

<details>
<summary>**Instructions**</summary>

Please complete the following two documents:

1. [[TEMPLATE] Personal Reflection 1 – 411B]({{< var personal-reflection-1-411B >}})
2. [[TEMPLATE] Peer and Self Evaluation - Mid quarter 411B]({{< var peer-and-self-evaluation-1-411B >}})

Detailed instructions are included in the templates.

This is an individual assignment. Each team member is responsible for submitting their own reflection and submitting it to the Box folder.

**If you would like to set up a meeting with me (Carmen) to chat about anything, please send me a Slack message and we can find a time that works.**

</details>


### 🗂 Update your GitHub org and repositories
**Due by next class, Wednesday, April 28.**

1. Use [this checklist](https://docs.google.com/document/d/10d9-h8UBC1JwZ08MdxI-WJhxfc7DnUolXjgBV1N-pJA/edit?usp=sharing) to update and clean your GitHub organization, repositories, and files by next class.

2. In [this spreadsheet](https://docs.google.com/spreadsheets/d/16T0eucIDxxn1Yed_7Xqw-ihqmmfJN3G1yHPBtNiTAfk/edit?usp=sharing), confirm this is still the URL for your GitHub organization. 

3. Make sure your code and repositories are public so they can be reviewed next week.

**Next class, we’ll have a round of in-class peer feedback for to review your GitHub files.**


### 📝 Update your Techincal Documentation

If you have already received feedback from your advisor:

- discuss feedback with your team
- start working on updating your draft
- contact advisors or clients for clarification and reply to comments within the document as needed. Remember to always do your research and discuss with your team first! 

