---
title: "Spring Week 2"
---

## Materials

📕 [Class slides]({{< var spring-week2-class-slides >}})

🗂️ [TD Outlines and Timeline shared folder]({{< var td-outlines-and-timeline >}})

💭 [In-class team reflections]({{< var team-reflections-411B >}})

📖 [Capstone guidelines]({{< var capstone-guidelines >}})

## Schedule

12:30 - 12:45: Questions, check-in, upcoming assignments

12:45 - 1:20: Peer feedback of Technical Documentation outline

1:20 - 1:25: Break

1:25 - 2:20: Dedicated work time & meetings with teams

2:20 - 2:30: Break

2:35 - 3:25: Dedicated work time & meetings with teams

3:25 - 3:30: Team reflections

## Upcoming deadlines

<script src="deadlines-data.js"></script>
<div id="table-spring-deadlines1"></div>
<script>
  document.addEventListener("DOMContentLoaded", () => {
    buildTable(r => r.week <= 7, "table-spring-deadlines1")
  });
</script>

## To do by next week

### 📝 1. Expand TD outline into preliminary draft

**Due when?** Before next class {{< var spring-week2-class >}}. We will use this document for an in-class activity.

**How to submit:** Add your document to our [shared TD Drafts folder]({{< var td-drafts-folder >}}). You can continue working on this document for your upcoming TD draft submission on {{< var td-preliminary-draft-deadline >}} !

<details>
<summary>**Instructions**</summary>

For each section: 

1. include as much information as completed to date. Clearly indicated placeholders or bulleted lists are acceptable at this point.
2. note the extent to which the section is completed and any remaining obstacles to its completion. 

As an appendix to the draft:

1. describe the work to be completed during the remainder of Spring Quarter 
2. include a timeline for remaining tasks and deliverables.


**We’ll have a round of peer feedback on this document next week.**

</summary>

### 🙌 2. ONGOING: Work on project implementation! 
