---
title: "Spring Week 3"
---

:::{.callout-caution appearance="minimal"}
## Next class 12:30-2:00 PM: Unit Testing Workshop

Workshop led by Sam Shanny-Csik on unit testing for dashboard development. 

- It will cover how to think about testing, regardless of the language. Conceptually, this will be relevant to all teams developing a dashboard. 
- All examples will be in R using `testthat`, `shiny`, and `shinytest2`.

 **Highly encouraged, but optional!** Discuss with your team whether it is relevant for your project. It’s ok if some team members attend and others don’t. 
 
 **We will all meet back in the classroom at 2:00 PM.**
:::

## Materials

📕 [Class slides]({{< var spring-week3-class-slides >}})

💭 [In-class team reflections]({{< var team-reflections-411B >}})

📖 [Capstone guidelines]({{< var capstone-guidelines >}})

## Schedule

12:30 - 12:45: Questions, Check-in, Upcoming Assignments

12:45 - 1:20: TBD

1:20 - 1:25: BREAK

1:25 - 2:25: Dedicated work time & meetings with teams

2:25 - 2:35: BREAK

2:35 - 3:25: Dedicated work time & meetings with teams

3:25 - 3:30: Team reflections


## Upcoming deadlines

{{< include _spring_deadlines_tables.qmd >}}

<div id="table-week1-7"></div>

## To do by next week


### 📥 Submit Technical Documentation Preliminary Draft

**Due when?** By 5 pm on {{< var td-preliminary-draft-deadline >}}.

**How to submit:** Send an email to your advisor and 411 instructor with a link to your Google doc. You can continue working on the document in our [shared TD Drafts folder]({{< var td-drafts-folder >}}).

<details>
<summary>**Instructions**</summary>

- Make the most out of this revision: it’s great to request specific feedback from your advisor! Is there any section you’d particularly like their input on? Let them know in your message. You can also tag us in comments inside your document.

**For each section:**

1. include as much information as completed to date. Clearly indicated placeholders or bulleted lists are acceptable at this point. 
2. note the extent to which the section is completed and any remaining obstacles to its completion. 

**As an appendix to the draft:**

1. describe the work to be completed during the remainder of Spring Quarter 
2. include a timeline for remaining tasks and deliverables.

</summary>

<br>

### 🙌 3. ONGOING: Work on project implementation! 